# font
font_family JetBrainsMono Nerd Font
font_size 12.0

# shell
shell .

# tweaks
enable_audio_bell no
cursor_shape block

# mouse
mouse_hide_wait 2.0

# cursor
cursor_shape block
cursor_trail 200
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
cursor_trail_color none

# tabs
tab_bar_min_tabs 2
tab_bar_edge top
tab_bar_margin_width 0.0
tab_bar_margin_height 2.0 2.0
tab_bar_style powerline
tab_powerline_style round

# notify
notify_on_cmd_finish invisible 10